name: Terraform CI/CD Pipeline for Deploying AWS Resources
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches:
      - main  # Removed quotes as they're not necessary here

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}        # Corrected variable name
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Fixed typo in secret name

jobs:
  build-infra:
    name: Terraform CI/CD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform-VPC  # Set default working directory for all steps
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to latest version (v4 as of March 2025)

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3  # Updated to latest version
        with:
          terraform_version: "1.7.5"  # Specify a specific version for consistency

      - name: Terraform Init
        id: init  # Fixed spacing
        run: terraform init

      - name: Terraform Validate
        id: validate  # Fixed spacing
        run: terraform validate

      - name: Terraform Plan
        id: plan  # Fixed spacing
        run: terraform plan -out=tfplan  # Added output file for apply step

      - name: Terraform Apply
        id: apply  # Fixed spacing
        run: terraform apply -auto-approve tfplan  # Use plan file for consistency
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve